### ISSUE TITLE
making an exception for nostalgia.wikipedia.org?

### ISSUE THREAD

**Issue by jeanbaptisteb** [adlerzei/old-wiki#1]
Hi,

Very neat extension, but here is a (very anecdotal) problem: 

The purpose of https://nostalgia.wikipedia.org is, among other things, to offer a very old layout of Wikipedia, as a snapshot of what it was in 2001. Its layout predates even the legacy vector skin. 

However, this extension overrides the original layout, which may be unfortunate, as it contradicts the purpose of the wiki (to be honest, I'm not entirely sure why this wiki allows the skin system).

Shouldn't the extension make an exception for this version of Wikipedia, even if I guess it has very few readers? (not a rhetorical question, I'm not sure if the answer should be 'yes it should').

Not entirely sure of how complicated it is to add an exception with the *declarative_net_request* method you use, even if I guess it might be trivial.

**Comment by adlerzei** [comment]
Thanks for the feedback. I can definitely add an exception for this subdomain. Should be easy to build.

**Comment by adlerzei** [comment]
Turns out regex support is very limited in declarativeNetRequest, so this is not as easy as expected. Unfortunately, the regex rule can also not easily combined with other rules of the ruleset. I might take a deeper look into this at a later date.

**Comment by jeanbaptisteb** [comment]
I think this is really an edge case, so nothing urgent, and anyway not a huge problem at all (to me at least. It's not like it's a critical thing to me, I just find that it would be a nice touch to this extension). Thanks anyway for taking the time to look into it.

**Comment by adlerzei** [comment]
Yeah, I aim to add a popup with a toggle to turn on/off the skin more easily. I guess this would be a nice feature for this issue, too.

**Comment by adlerzei** [comment]
Completed by toggle to turn the skin apply on and off in release v1.2.
