### ISSUE TITLE
Feature Request: Update the address bar once the page loads to remove the querystring

### ISSUE THREAD

**Issue by alextorma** [adlerzei/old-wiki#2]
It'd be like Vector skin is still the default, as it should be!

All jokes aside, I've forked this and added the functionality via a document_end content script (https://github.com/torma616/old-wiki/commit/05e12a8370714a60cf7afbee679a3b627a326e71). Happy to submit a PR if you want to incorporate this into the extension!

I haven't done any work to make this toggleable in the popup because to be totally honest I'm not sure exactly how to do that, but in my head, it doesn't seem that difficult in theory.

**Comment by adlerzei** [comment]
Feel free to submit a PR, thanks for your work!
