### ISSUE TITLE
Stops working on Brave browser after the browser is restarted

### ISSUE THREAD

**Issue by CentreMetre** [adlerzei/old-wiki#4]
When I restart the Brave browser the extension stops working. I would have to reinstall it for it to start working again. This doesn't happen on Chrome.
I tested it using the latest versions from installing from the Chrome extension store and loading an unpacked version manually on brave://extensions (both v1.3.0 6th Feb).
I can still manually add "?useskin=vector" on the end of a en.wikipedia.org URL.

**Comment by adlerzei** [comment]
Has been an issue in Brave and was fixed two weeks ago, please refer to: https://github.com/brave/brave-browser/issues/30854

Please update Brave to get rid of this issue.
